Debug: Test case scenario where definition is missing
Attempt to figure out why the definition is missing on a specific scenario:

```
$ go test -run TestOpenAPI2/typealias
--- FAIL: TestOpenAPI2 (0.03s)
    --- FAIL: TestOpenAPI2/typealias (0.03s)
        main_test.go:86: incorrect output:
            swagger: "2.0"
            info:
              title: x
              version: x
            consumes:
              - application/json
            produces:
              - application/json
            paths:
              /path:
                post:
                  operationId: POST_path
                  consumes:
                    - application/json
                  produces:
                    - application/json
                  parameters:
                    - name: typealias.ReqRef
                      in: body
                      required: true
                      schema:
                        $ref: '#/definitions/typealias.ReqRef'
                  responses:
                    200:
                      description: 200 OK (no data)
            definitions:
              typealias.ReqRef:
                title: ReqRef
                description: ReqRef is a request reference.
                type: object
                properties:
                  anonymous:
                    type: object
                    properties:
                      alias:
                        type: object
                        additionalProperties:
                          $ref: '#/definitions/typealias.ExampleItem'
        main_test.go:87: diff

            --- expected
            +++ actual
            @@ -37,13 +37,3 @@
                         additionalProperties:
                           $ref: '#/definitions/typealias.ExampleItem'
            -  typealias.ExampleItem:
            -    title: ExampleItem
            -    description: ExampleItem is an example item.
            -    type: object
            -    properties:
            -      properties:
            -        field1:
            -          type: string
            -        field2:
            -          type: integer

FAIL
exit status 1
FAIL	github.com/teamwork/kommentaar	1.220s
```